"""agentos CLI — minimal Agent OS governance runtime command-line interface.

Commands:
  init          Generate a default policy_config.yaml in the current directory.
  start-mcp     Start the MCP governance server on the given port.
  loop run      Forward a task to the Global-Loop-Engine via subprocess.
"""

from __future__ import annotations

import asyncio
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional

import click

logger = logging.getLogger(__name__)

# ── Default policy template ──

POLICY_TEMPLATE = """# ── Agent OS — Autonomy Policy ──
# Generated by `agentos init`. Edit to match your deployment constraints.
# All paths are relative to the workspace root.

version: "1.0"
description: "Default autonomy policy generated by agentos init"

filesystem:
  allowed_paths:
    - "./**"
    - "/tmp/agentos-poc/**"
  denied_paths:
    - "./.env"
    - "./.env.local"
    - "/etc/**"
    - "/var/**"

commands:
  mode: "allowlist"
  allowed:
    - "ls"
    - "cat"
    - "echo"
    - "pytest"
    - "python3"
    - "pip"
    - "git"
    - "docker"
  denied: []

write_quotas:
  max_operations_per_session: 50
  max_operations_per_minute: 10
  shacl_required_domains:
    - "it-asset-mgmt"

network:
  allowed_hosts:
    - "localhost:7687"
    - "localhost:8100"
  default_policy: "deny"

session:
  max_duration_seconds: 3600
  max_token_budget_usd: 0.50
"""


# ── CLI group ──


@click.group()
@click.option("-v", "--verbose", count=True, help="Increase verbosity.")
@click.version_option(version="0.1.0", prog_name="agentos")
def main(verbose: int) -> None:
    """agentos — Agent OS governance runtime CLI."""
    log_level = logging.DEBUG if verbose > 0 else logging.WARNING
    logging.basicConfig(
        level=log_level,
        format="%(levelname)s  %(name)s  %(message)s",
    )


# ── init ──


@main.command()
@click.option(
    "-o", "--output",
    default="policy_config.yaml",
    show_default=True,
    help="Output path for the generated policy config.",
)
@click.option(
    "-f", "--force",
    is_flag=True,
    help="Overwrite existing file without prompting.",
)
def init(output: str, force: bool) -> None:
    """Generate a default policy_config.yaml in the current directory."""
    path = Path.cwd() / output

    if path.exists() and not force:
        click.echo(
            f"❌ {path} already exists. Use --force to overwrite.",
            err=True,
        )
        sys.exit(1)

    path.write_text(POLICY_TEMPLATE, encoding="utf-8")
    click.echo(f"✅ Generated default policy config: {path}")


# ── start-mcp ──


@main.command()
@click.option(
    "--port",
    default=8100,
    show_default=True,
    help="Port for the MCP governance server.",
)
@click.option(
    "--host",
    default="0.0.0.0",
    show_default=True,
    help="Host address to bind the MCP server.",
)
@click.option(
    "--config",
    default=None,
    help="Path to agent-os config YAML file.",
)
def start_mcp(port: int, host: str, config: Optional[str]) -> None:
    """Start the MCP Governance Gateway server."""
    click.echo(f"🔌 Starting MCP governance server on {host}:{port}...")

    # Lazy imports to avoid loading heavy dependencies until needed
    try:
        from agentos.kernel.config import ConfigLoader
        from agentos.governance.schema_provider import SchemaProvider
        from agentos.governance.write_gate import WriteGate
        from agentos.governance.mcp_server import GovernanceGateway
    except ImportError as exc:
        click.echo(
            f"❌ Failed to import agentos.governance components: {exc}\n"
            f"   Ensure the agent-os package is installed correctly.",
            err=True,
        )
        sys.exit(1)

    # Load config
    config_path = config or os.environ.get("AGENT_OS_CONFIG", "config.yaml")
    try:
        loader = ConfigLoader(config_path)
        app_config = loader.load()
    except FileNotFoundError:
        click.echo(
            f"❌ Config file not found: {config_path}\n"
            f"   Create one or set AGENT_OS_CONFIG environment variable.",
            err=True,
        )
        sys.exit(1)

    # Override host/port if provided
    if host:
        app_config.mcp.host = host
    app_config.mcp.port = port

    # Bootstrap governance gateway
    schema_provider = SchemaProvider(
        owl_dir=app_config.ontology.owl_dir,
        shacl_dir=app_config.ontology.shacl_dir,
        domains=app_config.ontology.domains,
    )
    write_gate = WriteGate(
        schema_provider=schema_provider,
        neo4j_client=None,
        nonce_secret=app_config.mcp.validation.nonce_secret,
        nonce_ttl_seconds=app_config.mcp.validation.nonce_ttl_seconds,
    )
    gateway = GovernanceGateway(write_gate=write_gate, config=app_config)
    click.echo(f"✅ MCP server '{app_config.mcp.server_name}' ready on {host}:{port}")

    try:
        gateway.run()
    except KeyboardInterrupt:
        click.echo("\n⏹️  MCP server stopped.")


# ── validate ──


@main.command()
@click.option("--domain", required=True, help="Ontology domain (e.g. it-asset-mgmt).")
@click.option("--file", "data_file", required=True, type=click.Path(exists=True), help="Path to RDF data file (Turtle).")
@click.option("--config", default=None, help="Path to config YAML.")
def validate(domain: str, data_file: str, config: Optional[str]) -> None:
    """Validate RDF data and get a nonce."""
    try:
        from agentos.kernel.config import ConfigLoader
        from agentos.governance.schema_provider import SchemaProvider
        from agentos.governance.write_gate import WriteGate
    except ImportError as exc:
        click.echo(f"❌ Failed to import agentos.governance components: {exc}", err=True)
        sys.exit(1)

    config_path = config or os.environ.get("AGENT_OS_CONFIG", "config.yaml")
    loader = ConfigLoader(config_path)
    app_config = loader.load()

    schema_provider = SchemaProvider(
        owl_dir=app_config.ontology.owl_dir,
        shacl_dir=app_config.ontology.shacl_dir,
        domains=app_config.ontology.domains,
    )
    write_gate = WriteGate(
        schema_provider=schema_provider,
        neo4j_client=None,
        nonce_secret=app_config.mcp.validation.nonce_secret,
        nonce_ttl_seconds=app_config.mcp.validation.nonce_ttl_seconds,
    )
    
    with open(data_file, "r") as f:
        rdf_data = f.read().strip()

    report, nonce = write_gate.verify_shacl_compliance(domain, rdf_data)
    if report.is_valid:
        click.echo(f"✅ Validation passed. Nonce: {nonce}")
    else:
        click.echo(f"❌ Validation failed: {report.conforms}")
        sys.exit(1)


# ── write ──


@main.command()
@click.option("--domain", required=True, help="Ontology domain (e.g. it-asset-mgmt).")
@click.option("--nonce", required=True, help="Validation nonce.")
@click.option("--file", "data_file", required=True, type=click.Path(exists=True), help="Path to RDF data file (Turtle).")
@click.option("--config", default=None, help="Path to config YAML.")
def write(domain: str, nonce: str, data_file: str, config: Optional[str]) -> None:
    """Execute a governed write to the database."""
    try:
        from agentos.kernel.config import ConfigLoader
        from agentos.governance.schema_provider import SchemaProvider
        from agentos.governance.write_gate import WriteGate
        from agentos.governance.neo4j_client import Neo4jClient
        from agentos.policies.autonomy_policy import load_policy
        from agentos.kernel.kernel import AgentOSKernel, ChannelMessage
    except ImportError as exc:
        click.echo(f"❌ Failed to import agentos.governance components: {exc}", err=True)
        sys.exit(1)

    config_path = config or os.environ.get("AGENT_OS_CONFIG", "config.yaml")
    loader = ConfigLoader(config_path)
    app_config = loader.load()

    async def _do_write():
        neo4j_client = Neo4jClient(app_config.neo4j)
        try:
            await neo4j_client.health_check()
            schema_provider = SchemaProvider(
                owl_dir=app_config.ontology.owl_dir,
                shacl_dir=app_config.ontology.shacl_dir,
                domains=app_config.ontology.domains,
            )
            write_gate = WriteGate(
                schema_provider=schema_provider,
                neo4j_client=neo4j_client,
                nonce_secret=app_config.mcp.validation.nonce_secret,
                nonce_ttl_seconds=app_config.mcp.validation.nonce_ttl_seconds,
            )
            policy = load_policy(app_config.autonomy.policy_file)
            kernel = AgentOSKernel(config=app_config, write_gate=write_gate, autonomy_policy=policy)
            
            with open(data_file, "r") as f:
                rdf_data = f.read().strip()
                
            msg = ChannelMessage(
                text=f"execute_governed_write {domain} {nonce}\n{rdf_data}",
                sender_id="cli-user",
                sender_name="CLI",
                channel="cli"
            )
            response = await kernel.wake_up(msg)
            if response.metadata.get("status") == "error" or response.error:
                click.echo(f"❌ Write failed: {response.text}", err=True)
                sys.exit(1)
            click.echo(f"✅ {response.text}")
        finally:
            await neo4j_client.close()

    asyncio.run(_do_write())


# ── loop ──


@main.group()
def loop() -> None:
    """Forward tasks to the Global-Loop-Engine (GLE)."""


@loop.command()
@click.option("--task", required=True, help="Task description for the loop engine.")
@click.option(
    "--mode",
    default="auto",
    show_default=True,
    help="GLE execution mode (auto, validate, execute).",
)
def run(task: str, mode: str) -> None:
    """Run a task through the Global-Loop-Engine subprocess."""
    # --- PATH detection for loop-engine ---
    loop_engine = _find_loop_engine()
    if loop_engine is None:
        click.echo(
            "❌ loop-engine not found in PATH.\n"
            "   Please run: pip install agent-os-cli[loop] to enable this feature.",
            err=True,
        )
        sys.exit(1)

    click.echo(f"🔄 Forwarding task to loop-engine (mode={mode})...")
    try:
        result = subprocess.run(
            [loop_engine, "--task", task, "--mode", mode],
            capture_output=True,
            text=True,
            timeout=300,
        )
    except FileNotFoundError:
        click.echo(
            "❌ loop-engine executable not found.\n"
            "   Please run: pip install agent-os-cli[loop] to enable this feature.",
            err=True,
        )
        sys.exit(1)
    except subprocess.TimeoutExpired:
        click.echo("❌ loop-engine timed out after 300 seconds.", err=True)
        sys.exit(1)

    # Print stdout/stderr
    if result.stdout:
        click.echo(result.stdout)
    if result.stderr:
        click.echo(result.stderr, err=True)

    if result.returncode == 0:
        click.echo(f"✅ loop-engine completed (exit code 0)")
    else:
        click.echo(
            f"❌ loop-engine failed with exit code {result.returncode}",
            err=True,
        )
    sys.exit(result.returncode)


# ── Helper ──


def _find_loop_engine() -> Optional[str]:
    """Search PATH for the loop-engine executable.

    Returns the full path if found, None otherwise.
    """
    path_dirs = os.environ.get("PATH", "").split(os.pathsep)
    for directory in path_dirs:
        candidate = Path(directory) / "loop-engine"
        if candidate.is_file() and os.access(str(candidate), os.X_OK):
            return str(candidate)
    return None


if __name__ == "__main__":
    main()
